---
title: "Тест русского в графиках"
author: "Boris Demeshev"
date: "`r Sys.Date()`"
lang: ru-RU
otherlangs: en-GB
fontsize: 11pt
biblio-style: alphabetic
mainfont: "Linux Libertine O"
sansfont: "Linux Libertine O"
monofont: "Linux Libertine O"
link-citations: yes
description: "Демо файл Rmd с кучей настроек и русскими буквами"
output: 
  pdf_document:
    fig_caption: yes
    highlight: tango
    keep_tex: yes
    latex_engine: xelatex
    citation_package: biblatex
    number_sections: yes
    toc: yes
header-includes: 
  - \newfontfamily{\cyrillicfonttt}{Linux Libertine O}
  - \newfontfamily{\cyrillicfont}{Linux Libertine O}
  - \newfontfamily{\cyrillicfontsf}{Linux Libertine O}
---

```{r setup, include=FALSE}
library("knitr")
library("tikzDevice")

# tikz plots options
options(tikzDefaultEngine = "xetex")
# options(tikzMetricsDictionary = getwd()) # cash font metrics for speed

add_xelatex <- c("\\defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}",
"\\setmainfont{Linux Libertine O}",
"\\setmonofont{Linux Libertine O}",
"\\setsansfont{Linux Libertine O}",
"\\newfontfamily{\\cyrillicfonttt}{Linux Libertine O}",
"\\newfontfamily{\\cyrillicfont}{Linux Libertine O}",
"\\newfontfamily{\\cyrillicfontsf}{Linux Libertine O}")

options(tikzXelatexPackages = c(getOption("tikzXelatexPackages"),
    add_xelatex))                            

opts_chunk$set(dev = "tikz", 
               dev.args = list(pointsize = 11))

```

даёшь русский везде!

```{r}
library("ggplot2") # вперёд
qplot(rnorm(100)) + xlab("Ось абсцисс, $\\sqrt{x}$")
```


