---
title: "Шаблон для ЭЖ ВШЭ"
author: "Винни-Пух"
date: "21 April 2017"
output:
  word_document:
    reference_docx: ej_shablon.docx
  pdf_document: default
  html_document: default
annotation: Привет всем!
jelcodes: C11, C32, C53
keywords: BVAR, априорные распределения, точечное прогнозирование, прогнозирование
  плотности
lang: ru-RU
bibliography: demo.bib
abstract: Фигня полная
csl: ej_similar_bibliography.csl
---

# Новое эссе

Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в (Doan et al., 1984).
Ковариационная матрица   вектора   предполагается диагональной и постоянной. Априорное распределение параметров предполагается многомерным нормальным, зависящим от нескольких гиперпараметров. Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в (Doan et al., 1984).

Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в [@einstein1935can].
Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений[^1] параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в (Doan et al., 1984).

[^1]: Ура! Сноска!


## Только вперёд!

ваыаыаыв адылв адыовдаоыдв аодыв оадылв оадыв а


[Примеры стилей списка литературы](https://www.zotero.org/styles)

ыв аолы вла ыовла лыв оалы овлаоыв

Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в [@einstein1935can].
Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в [@einstein1935can].
Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в [@einstein1935can].

Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в [@einstein1935can].
Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в [@einstein1935can].

Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в [@einstein1935can].
Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в [@einstein1935can].

Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в [@einstein1935can].
Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в [@einstein1935can].

Решение проблемы избыточной идентификации на основе байесовских методов было предложено в работе (Litterman, 1979), где было показано, что введение ограничений в форме априорных распределений параметров увеличивает точность оценок и прогнозов. Априорное распределение, получившее название «априорное распределение Миннесоты», было предложено в работе (Litterman, 1986) и с некоторыми модификациями в [@einstein1935can].

### И только вперед (3)

выаываыв

## Литература





